### ISSUE TITLE
not supported retina display on google chrome

### ISSUE THREAD

**Issue by keshav7** [JetBrains/jediterm#113]
Hi Plonk and Traff
I have been using jediterm as an applet on a small web application. I have been using it on MAC book pro retina on firefox. However when i use it on chrome, the text is not sharp. Can you please provide the solution for the same.

Thanks and Regards
Keshav

**Comment by abarrafo** [comment]
@keshav7 I am interested in porting jediterm as a browser applet. Can you share your code and implementation that works?
