### ISSUE TITLE
Is there anyway to run a command in this terminal from another plugin?

### ISSUE THREAD

**Issue by wangyanxing** [JetBrains/jediterm#116]
I am writing a IntelliJ plugin and I want to run a command in your terminal. Do you have some interfaces to do it? 

Thanks a lot!

**Comment by Plonk42** [comment]
You can have a look on how the terminal is integrated into Intellij here : https://github.com/JetBrains/intellij-community/tree/master/plugins/terminal/src/org/jetbrains/plugins/terminal

To "run command" you'll need to feed the command string to the terminal [TTYConnector](https://github.com/JetBrains/jediterm/blob/master/src-terminal/com/jediterm/terminal/TtyConnector.java). 

The easiest way it to use the `write(String string)` method. 
This will act exactly the same as if you were typing by hand in the terminal.
Don't forget a trailing "\n" at the end of you command to simulate the "Enter" key.

**Comment by wangyanxing** [comment]
Sweet! Thanks
