### ISSUE TITLE
Erase in Line CSI sequence does not erase line content beyond the terminal width

### ISSUE THREAD

**Issue by rprichard** [JetBrains/jediterm#118]
I noticed that with jediterm, the Erase in Line CSI sequence (`\x1b[<n>K`) only erases the currently visible part of the line.  If the line extends past the right end of the window, those characters aren't erased.  If the window is later expanded horizontally, the previously invisible part of the erased line comes back into view.

This behavior seems wrong to me.  It also doesn't match what other terminals do (particularly, xterm, VTE, and Konsole).

Like jediterm, xterm also keeps track of obscured line content beyond the right edge of the terminal, but both `\x1b[0K` and `\x1b[2K` erase the obscured characters.

Example:

 - Resize a terminal to (say) 50x50.
 - Run: echo -e '\x1b[2J\x1b[1;1HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
 - Reduce the terminal's width so that the AAA string is truncated.
 - Run: echo -e '\x1b[1;1H\x1b[2K'
 - Increase the terminal's width.

FWIW: This issue is affecting my winpty project, which frequently rewrites lines when the terminal/console is resized.

**Comment by rprichard** [comment]
I filed the same issue against mintty: https://github.com/mintty/mintty/issues/480

**Comment by traff** [comment]
Hi Ryan!
Thanks for the reporting, I'll look into it.

**Comment by traff** [comment]
Fixed:
CSI K Erase in Line
CSI J Erase in Display
CSI X Erase Characters
CSI P Delete Characters

**Comment by traff** [comment]
Ryan, does that mean that I can try to sync my winpty fork with your latest changes? Or it's not related?

**Comment by rprichard** [comment]
I'd say my recent winpty changes are unrelated.  i.e. After this jediterm change, winpty should work a little bit better (scrollback has a bit less junk in it), but I think that applies to both old and new versions of winpty.

That said, I've made a few improvements recently that might be nice to incorporate into your version.  I'm planning some other improvements in the near future as well (e.g. reducing the polling that the agent performs).

I'd like to reduce the delta between our two versions if possible, if only to make merging easier.  IIRC, the biggest difference has to do with the "console mode", whose intended use case I'm unclear on.  Could you point me to where IntelliJ uses the winpty console mode?  Thanks!

**Comment by traff** [comment]
Ok, then I think it makes sense to wait till you finish your improvements and then update IntelliJ platform to the latest version.

Actually, the best thing would be not to have our own fork at all, so if it possible to merge them we should do that.

We use console mode for the case when PTY is needed for a process to launch, but there is no terminal that handles escape sequences. Instead of a terminal the process output is shown in a normal IDE console tool window.

You can track it's usages by looking at the PtyCommandLine class in IntelliJ platform code, it has myConsoleMode = true by default.
