### ISSUE TITLE
It doesnot work properly with chinese characters.

### ISSUE THREAD

**Issue by jstdoit** [JetBrains/jediterm#119]
As show in the snapshot, it only show half of the character.
![image](https://cloud.githubusercontent.com/assets/1089041/10273156/c300d916-6b5e-11e5-978c-26d95271fd80.png)

**Comment by mytoolkitcn** [comment]
you can try to modify the `CharUtils.isDoubleWidthCharacter` method
```
    private static boolean isDoubleWidthCharacter(char c) {
    	 if (Character.isLetter(c)  && Character.UnicodeBlock.of(c) == 
                    Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS) {  
             return true;
         } 

        return false; //  TODO: use FontMetrics to determine the correct width after refactoring
        // as for now double width chars aren't fully supported anyway
    }
```

**Comment by jstdoit** [comment]
you do mean to recompile the jediterm?

**Comment by CALTyang** [comment]
Do you mean modify the CharUtils,and use `ant all-jars` to get the jar file and replace what in IDEA plugins/terminal/lib folder?

**Comment by boreas320** [comment]
com.jediterm.terminal.ui.TerminalPanel#drawCharacters

also has some problems with the calculation of x coordinate.
When comment the invoke of `java.awt.Graphics#fillRect ` in `    com.jediterm.terminal.ui.TerminalPanel#drawCharacters`,cjk chars
would show normally with the missing of cursor.

**Comment by traff** [comment]
This should be fixed now.
