### ISSUE TITLE
Closing a tab leaves the child process running (on both Linux and Windows)

### ISSUE THREAD

**Issue by rprichard** [JetBrains/jediterm#134]
cc @Plonk42 

The title sums it up, more or less.  On Linux, I tested by:
 - Start a second session (File -> New Session)
 - Start a Python interpreter in the new sesson.
 - Check for the Python process using "pidof python".
 - Close the session using the context menu.
 - Check for the Python process using "pidof python".  It's still running.

I think the bug was introduced in this commit, https://github.com/JetBrains/jediterm/commit/eb490a0dc61d077d13e68efb7cd7d3599039a7ef.  That commit factored out code from a termination callback and from `close` into a new `closeTab` function.  The `closeTab` function doesn't call `JediTermWidget.close`, but the old `close` function did.  `JediTermWidget.close` calls `TerminalStarter.close`, which calls `TtyConnector.close` (as well as shut down the `ExecutorService`).  `ProcessTtyConnector.close` is responsible for destroying the PtyProcess and closing I/O streams.

There is a "Connector" thread that calls `TerminalStarter.start`, which blocks until the `Process.getInputStream()` reaches EOF.  With both the Unix and Windows pty4j implementations, once the child process exits, the `Process`'s input stream soon reaches EOF (after any existing data is removed from the pty).  Once that happens, the Connector thread calls `myTtyConnector.close();`

Maybe the fix is to simply add a `terminal.close()` call:

```diff
diff --git a/src-terminal/com/jediterm/terminal/ui/TabbedTerminalWidget.java b/src-terminal/com/jediterm/terminal/ui/TabbedTerminalWidget.java
old mode 100644
new mode 100755
index fe00071..1fed355
--- a/src-terminal/com/jediterm/terminal/ui/TabbedTerminalWidget.java
+++ b/src-terminal/com/jediterm/terminal/ui/TabbedTerminalWidget.java
@@ -190,6 +190,7 @@ public class TabbedTerminalWidget extends JPanel implements TerminalWidget, Term

   public void closeTab(final JediTermWidget terminal) {
     if (terminal != null) {
+      terminal.close();
       if (myTabs != null) {
           SwingUtilities.invokeLater(new Runnable() {
             @Override
```

**Comment by Plonk42** [comment]
Thanks @rprichard for the report and analysis. 

You are right `terminal.close()` is missing. However, I will not add it to `closeTab()`, but to `closeCurrentSession()`:
- `closeTab()` is really about the UI, called when the underlying session is already closed, and the tab needs to be removed
- `closeCurrentSession()` by opposite should actually close the *session* (ie. the process), not the widget (the UI). **This** is our bug.  `TtyConnectorWaitFor` created by `setupTtyConnectorWaitFor()` is responsible of removing the tab by calling `closeTab()`, when the session is closed. BTW, a side effect is that `closeCurrentSession()` is not honoring `TabbedSettingsProvider.shouldCloseTabOnLogout()`.

I will submit this patch:

```diff
diff --git a/src-terminal/com/jediterm/terminal/ui/TabbedTerminalWidget.java b/src-terminal/com/jediterm/terminal/ui/TabbedTerminalWidget.java
index fe00071..34edca0 100644
--- a/src-terminal/com/jediterm/terminal/ui/TabbedTerminalWidget.java
+++ b/src-terminal/com/jediterm/terminal/ui/TabbedTerminalWidget.java
@@ -206,5 +206,5 @@
 
   public void closeCurrentSession() {
-    closeTab(getCurrentSession());
+    getCurrentSession().close();
   }
```

**Comment by rprichard** [comment]
IntelliJ has an option under "Tools > Terminal" called "Close session when it ends", which I think is what controls the `shouldCloseTabOnLogout()` setting.  It seems that "close session" is treated as synonymous with "close the tab."  I think `closeCurrentSession()` is called everywhere that a tab is closed (e.g. middle-clicking the active tab in IntelliJ, right-click and "Close Session", the IntelliJ Close Session button).

i.e. Once I make that change, if I have the "Close session when it ends" setting on, then I can't ever close a terminal tab.

**Comment by Plonk42** [comment]
OK, I see what you mean. 

There might by a confusion here due to the name of this function. @traff can you confirm the role of `closeCurrentSession()` is to close the session **and** remove the terminal, independently of the value of `shouldCloseTabOnLogout()`? If yes, then my patch is not enough.

Also, if we remove the tab in `closeCurrentSession()`, the `TtyConnectorWaitFor` will try to remove it a second time (with `shouldCloseTabOnLogout() == true`).  We need to check this is not a problem.

**Comment by traff** [comment]
@rprichard  Thanks for the bug report, indeed that is something I missed during the review...
Hi @Plonk42, I confirm that `closeCurrentSession()` is currently used to close both the tab and the session independently of the value of `shouldCloseTabOnLogout()`. `shouldCloseTabOnLogout()` was intended to regulate how the whether the tab should be removed in case the session is closed from the shell side. In case of the close on the UI side it seems that it is always desirable to remove the tab.

**Comment by Plonk42** [comment]
Thanks @traff. I've pushed a new patch to restore this behavior. 

I've also added a check based on `indexOfComponent()` to avoid remove the tab multiple times (`TtyConnectorWaitFor` will still try to remove the tab, even if already removed), to prevent triggering multiple times `fireTabClosed()`.
