### ISSUE TITLE
Ctrl+K behaves like Ctrl+L instead of delete until end of line

### ISSUE THREAD

**Issue by jdahlin** [JetBrains/jediterm#139]
How to reproduce:
1. Open a terminal in PyCharm 2016.2.3 for Linux (which embeds jediterm-pty-2.2.jar)
2. Write a few characters
3. Go to beginning of line (Ctrl+A)
4. Press Ctrl+K

Expected behavior:
The reset of the line is deleted.

Actual behavior:
Line is cleared, very much like if Ctrl+L has been pressed.

Discussion:
Some other readline shortcuts: Ctrl+A, Ctrl+L, Ctrl+R works fine, but not all of them:

These ones do not work, at the very least using the default configuration.
Ctrl+E: end of line
Ctrl+F: forward-character
Ctrl+G: backward-character
Alt+F: forward-word
Alt+B: backward-word

Not sure if this should be reported in PyCharm or jediterm, Let me know if I should file this elsewhere.

**Comment by nickthecoder** [comment]
This bug also appears in the terminal of IntelliJ Idea 2017.2. (so is not related to PyCharm).

When pressing Ctrl+K from my own application using jediterm, I see this error message :
ERROR [AWT-EventQueue-0] (TerminalTextBuffer.java:255) - Attempt to get line out of bounds: -1 < 0

**Comment by dfernan** [comment]
any ways to solve this issue?

**Comment by tuus-amicus** [comment]
Still have no solutions? Always use CTRL + <key> terminal's mappings and i'm used to it. :syringe:

**Comment by kpe** [comment]
ALT+f and ALT+b don't work for me either in PyCharm's terminal (it's like if ALT gets stripped and not passed to the shell) - that's really a showstopper.

**Comment by tuus-amicus** [comment]
@kpe 
Good solution, but not workable for me. Would like to setup settings work properly. Besides, on Mac these key bindings work well. Face this issue only on linux machine. There is may be solution. Hope, someone will tell.

**Comment by kpe** [comment]
just a minor update - to get `CTRL+K` working, I replaced `CTRL+K` and `CTRL+L` in `DefaultSettingsProvider.java` like this (note the `UIUtil.isMac`):
```diff

--- a/terminal/src/com/jediterm/terminal/ui/settings/DefaultSettingsProvider.java
+++ b/terminal/src/com/jediterm/terminal/ui/settings/DefaultSettingsProvider.java
@@ -45,9 +45,12 @@ public class DefaultSettingsProvider implements SettingsProvider {

   @Override
   public KeyStroke[] getClearBufferKeyStrokes() {
-    return new KeyStroke[]{UIUtil.isMac
-            ? KeyStroke.getKeyStroke(KeyEvent.VK_K, InputEvent.META_DOWN_MASK)
-            : KeyStroke.getKeyStroke(KeyEvent.VK_K, InputEvent.CTRL_DOWN_MASK)};
+      return new KeyStroke[]{KeyStroke.getKeyStroke(KeyEvent.VK_L, InputEvent.CTRL_DOWN_MASK)};
+//
+//  return new KeyStroke[]{UIUtil.isMac
+//            ? KeyStroke.getKeyStroke(KeyEvent.VK_K, InputEvent.META_DOWN_MASK)
+//            : KeyStroke.getKeyStroke(KeyEvent.VK_K, InputEvent.CTRL_DOWN_MASK)};
+//
   }

   @Override
@@ -188,7 +191,7 @@ public class DefaultSettingsProvider impalso lements SettingsProvider {

   @Override
   public boolean altSendsEscape() {
-    return false;
+    return true;
   }
```
i.e., replacing VK_K with VK_L (which frees CTRL+K and sets CTRL+L where it belongs). 
With those changes, I'm ready to give PyCharm a second chance :-)

**Comment by FrankFang** [comment]
using ctrl +Q or ctrl + W for now.
But I miss ctrk + K very much!
