### ISSUE TITLE
2-bytes ST not recognized as system command termination

### ISSUE THREAD

**Issue by alekitto** [JetBrains/jediterm#185]
`SystemCommandSequence` does recognize only the C1 control code `0x9C` or the `BEL` character as the OSC termination, but fails to parse the 2-bytes sequence `ESC \` not resetting the terminal status.

The sequence to print a text with a link

```sh
$ echo -e '\x1B]8;;http://example.org\x1B\\Test link\x1B]8;;\x1B\\ Test test'
```

produces `Test link Test test` (with hyperlink upon "Test link") on iTerm, but nothing on jediterm, whereas `Test link Test test` was expected as the `ST` sequence is present just before the first text.

In running processes using the ST sequence this will block the output until the process exits.

**Comment by segrey** [comment]
https://youtrack.jetbrains.com/issue/IDEA-204536
