### ISSUE TITLE
Change terminal directory license?

### ISSUE THREAD

**Issue by rabelenda** [JetBrains/jediterm#192]
Is there any chance to change `terminal` directory license to be apache 2 licensed? 

I am evaluating using the code on that directory for an open source project, but the project uses apache 2 license and lgpl dependencies can't be used from apache 2 projects according to this http://www.apache.org/legal/resolved.html#category-x.

Thank you very much for this nice piece of software and code.

**Comment by traff** [comment]
JediTerm used to have some parts of it licensed under LGPL-3 and some parts under Apache-2.0. Now we fixed that by dual-license and allowing to choose between the two licenses.
