### ISSUE TITLE
Terminal does not correctly output certain ANSI styles

### ISSUE THREAD

**Issue by JackWH** [JetBrains/jediterm#196]
When using JediTerm as it is currently integrated with PhpStorm 2020.1, I noticed some styled output in the Terminal tool does not render correctly. However, it renders correctly on the macOS Terminal.

I double-checked the environment variables, shell settings, and `infocmp` output in both environments, and everything was matched correctly, so I guess this must be a JediTerm bug.

See below for a screenshot of how a few common escape sequences look. Specifically, it's italic and dim settings that don't seem to be applied. 

<img width="1251" alt="Terminal Outputs" src="https://user-images.githubusercontent.com/627533/79664568-19c6b680-81ad-11ea-9c09-b1de096a9f27.png">

**Comment by segrey** [comment]
Thanks for reporting. It will be fixed in 2021.2.
