### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by BeichenDream** [JetBrains/jediterm#204]
When using jediterm, I found that the font spacing is very large. How to solve this

![ttybug](https://user-images.githubusercontent.com/43266206/120217052-5eef6000-c26a-11eb-9db5-d8fd6f9454f1.jpg)

**Comment by BeichenDream** [comment]
```
        JediTermWidget jediTerminal=new JediTermWidget(new DefaultSettingsProvider() {
            @Override
            public Font getTerminalFont() {
                try {
                    return Font.decode("微软雅黑").deriveFont(14f);
                }catch (Exception e){
                    e.printStackTrace();
                    return null;
                }
            }

            @Override
            public float getTerminalFontSize() {
                return 14;
            }
        });

        jediTerminal.getTerminal().writeCharacters("你好 Hello!");
        jediTerminal.getTerminal().nextLine();
```

**Comment by HugoGDRM** [comment]
Hi, I'm sorry because I can't help you right now, I need to integrate this terminal into my project -> an IDE in JAVA, the problem is that I don't know how to use it, I have find any documentation and when I try to add a JediTermWidget to my Jpanel I got this error.
![unknown](https://user-images.githubusercontent.com/52536753/122268012-d9abb280-cedb-11eb-96fa-37f3ab3001bd.png)

Thanks for your help bro

**Comment by segrey** [comment]
@HugoGDRM You also need to add log4j to the classpath, see all dependencies [here](https://github.com/JetBrains/jediterm/blob/master/pty/build.gradle#L17-L21).

**Comment by segrey** [comment]
@BeichenDream That's expected, because painting uses same character width for all symbols. Character width is calculated [here](https://github.com/JetBrains/jediterm/blob/master/terminal/src/com/jediterm/terminal/ui/TerminalPanel.java#L662).

**Comment by BeichenDream** [comment]
I think as a component, it should automatically calculate the character width based on the range of char

**Comment by segrey** [comment]
Maybe. But it would complicate the painting mechanism. Also, it would cost some performance. Support for non-monospaced fonts is not in the immediate plans.

**Comment by BeichenDream** [comment]
I have one more question

When I can’t draw with other fonts, how to make it use the system default font to draw. For example, the string "Hello hello" When the font only supports English, the substring "Hello" will become a square

**Comment by segrey** [comment]
Currently, the only way is to use font supporting all needed characters. If it's not possible, please open a new feature request and describe your use case. Thanks.
