### ISSUE TITLE
How to set up to support Chinese display

### ISSUE THREAD

**Issue by G3G4X5X6** [JetBrains/jediterm#215]
`com/jediterm/example/BasicTerminalShellExample.java `
![image](https://user-images.githubusercontent.com/87740076/130021384-626c9a09-50c9-4225-bbfc-1dc3ef4576c9.png)

**Comment by segrey** [comment]
Will it help to replace `StandardCharsets.UTF_8` with `Charset.defaultCharset()`?
https://github.com/JetBrains/jediterm/blob/7e42fc1261ffd0b593557afa71851f1d1df76804/JediTerm/src/main/java/com/jediterm/example/BasicTerminalShellExample.java#L39

**Comment by G3G4X5X6** [comment]
something changed, but didn't work
![image](https://user-images.githubusercontent.com/87740076/130031090-680d0b16-80da-4634-8a84-0aa8f8975d12.png)

**Comment by segrey** [comment]
What is printed in a system terminal, e.g. Windows Terminal?
What's the value of `Charset.defaultCharset()`?
What's your "Current system locale" (see "Region" dialog in your Windows settings)?
For example, here is how it looks for me:
![image](https://user-images.githubusercontent.com/607109/130038742-ec768647-0271-43fb-bc66-344356e1f07b.png)

**Comment by G3G4X5X6** [comment]
## Windows Terminal
![image](https://user-images.githubusercontent.com/87740076/130040408-a0e82695-19c8-4dc6-a922-e85c154a123f.png)

## Charset.defaultCharset()
![image](https://user-images.githubusercontent.com/87740076/130040747-30632f6d-e518-461b-885f-860e0fb8aa9e.png)

## Current system locale
![image](https://user-images.githubusercontent.com/87740076/130040270-0c8e4712-52cc-4f25-9096-edcf89eeed35.png)

**Comment by G3G4X5X6** [comment]
## Set Charset.defaultCharset()
![image](https://user-images.githubusercontent.com/87740076/130042074-7aec02a8-ef09-4fd9-830e-d031d27f016e.png)

## Running
![image](https://user-images.githubusercontent.com/87740076/130042390-7bc430b6-572a-4201-8826-af9e24b58111.png)

----

## Set StandardCharsets.UTF_8

![image](https://user-images.githubusercontent.com/87740076/130042824-d32141a8-0886-41d2-95c6-731e6d76041e.png)

## Running

![image](https://user-images.githubusercontent.com/87740076/130043155-4681fff1-60fb-4e80-b84c-719f9378e0f0.png)

**Comment by segrey** [comment]
Thanks. Will it help to replace `new String[]{"cmd.exe"}` with `new String[]{"cmd.exe", "/U"}`?

https://github.com/JetBrains/jediterm/blob/7e42fc1261ffd0b593557afa71851f1d1df76804/JediTerm/src/main/java/com/jediterm/example/BasicTerminalShellExample.java#L31

What's the output of `chcp` command?

**Comment by G3G4X5X6** [comment]
![image](https://user-images.githubusercontent.com/87740076/130048721-6edbf88b-6430-4963-8fc6-69b3101826e3.png)

**Comment by segrey** [comment]
Maybe the problem is with font. Please change `com.jediterm.terminal.ui.settings.DefaultSettingsProvider#getTerminalFont` to a font supporting Chinese. Will it help?

**Comment by G3G4X5X6** [comment]
thanks. it work.
