### ISSUE TITLE
Changing the Whole Color Palatte

### ISSUE THREAD

**Issue by omegaui** [JetBrains/jediterm#234]
Hi!
I am working on an [IDE](https://omegaui.github.io/omegaide)

It already has a minimal integrated terminal!

And I'm looking forward to add **Jediterm** into the IDE.

The thing is I want to change the **Entire ColorPalette** of the Terminal for the **Dark Mode**.
But I don't know how to do that.
I already saw **DefaultSettingsProvider** but I am unable to figure out how to implement the Color part.
Please tell me how can I do that!

The **Light Mode** already looks great!

![Screenshot from 2021-11-24 14-43-08](https://user-images.githubusercontent.com/73544069/143209427-7c43b9e7-346b-468c-be8a-91ffc960b60f.png)

But the Dark Mode looks like this
![Screenshot from 2021-11-24 14-41-19](https://user-images.githubusercontent.com/73544069/143209707-f0ad1375-d9e0-4065-b5b8-c404f3262947.png)

Also, I want to know how can I use the default terminal profiles(on linux) for Jediterm!

🙂

**Comment by omegaui** [comment]
Ok! I figured it out

```
package omega.terminal.jediterm;
import omega.utils.UIManager;

import com.jediterm.terminal.TextStyle;

import java.awt.Font;
import java.awt.Color;

import com.jediterm.terminal.emulator.ColorPalette;

import javax.swing.KeyStroke;

import com.jediterm.terminal.ui.settings.DefaultSettingsProvider;

import static omega.utils.UIManager.*;

public class JetTermSettingsProvider extends DefaultSettingsProvider{

	public static Color[] colors = new Color[16];
	static{
		colors[0] = glow;
		colors[1] = TOOLMENU_COLOR2;
		colors[2] = TOOLMENU_COLOR1;
		colors[3] = TOOLMENU_COLOR5;
		colors[4] = TOOLMENU_COLOR3;
		colors[5] = Color.decode("#FF8C42");
		colors[6] = Color.decode("#FBB13C");
		colors[7] = Color.decode("#D81159");
		colors[8] = Color.decode("#E0777D");
		colors[9] = Color.decode("#8E3B46");
		colors[10] = Color.decode("#A2AD59");
		colors[11] = Color.decode("#92140C");
		colors[12] = Color.decode("#253237");
		colors[13] = Color.decode("#5C6B73");
		colors[14] = Color.decode("#4C2719");
		colors[15] = back2;
	}
	
	@Override
	public Font getTerminalFont() {
		return new Font(UIManager.fontName, UIManager.fontState, UIManager.fontSize);
	}
	
	@Override
	public float getTerminalFontSize() {
		return UIManager.fontSize;
	}
	
	@Override
	public boolean useInverseSelectionColor() {
		return true;
	}

	@Override
	public ColorPalette getTerminalColorPalette() {
		return new ColorPalette(){
			@Override
			public Color[] getIndexColors(){
				return colors;
			}
		};
	}
	
	@Override
	public boolean useAntialiasing() {
		return true;
	}
	
	@Override
	public boolean audibleBell() {
		return true;
	}
	
	@Override
	public boolean scrollToBottomOnTyping() {
		return true;
	}
	
}

```

**Comment by segrey** [comment]
@omegaui That's right, you need to override `DefaultSettingsProvider#getTerminalColorPalette` and implement `com.jediterm.terminal.emulator.ColorPalette#getForegroundByColorIndex` and `#getBackgroundByColorIndex` to return colors suitable for current IDE theme.

>Also, I want to know how can I use the default terminal profiles(on linux) for Jediterm!

I'm unaware of a common way to retrieve such information. Seems the logic should be specific for each particular terminal implementation, e.g. for GNOME Terminal.
