### ISSUE TITLE
Poor Performance on the Windows Platform

### ISSUE THREAD

**Issue by omegaui** [JetBrains/jediterm#241]
@segrey 
I have been testing my application on different platforms and I found that

Jediterm is **running fine** on Ubuntu 20.04 but is **lagging a lot** on Windows 10 21H1 with the same hardware specs.

The System's Specs:
4 GB RAM (3.88 GB Usable on Windows and 3.7 GB usable on Ubuntu)
Intel Pentium 2 Cores 2.20 GHz each

On Windows : the process launched is `cmd.exe` //Or I should use powershell.exe will it effect the performance?
On Linux : the process launched is `bash`

It works as fast as the gnome-terminal on Ubuntu but lags a lot (**really a lot**) on Windows 10.

First, It takes around 10 -15 seconds to load when launch is triggered.
Second, it takes much time(around 5 seconds or more) to display the characters and to trigger any key strokes on the component.
Third, it takes a lot of time to display the output.

Even the normal `dir` command's output takes ages to load.

**Comment by omegaui** [comment]
![Screenshot from 2022-02-09 15-15-07](https://user-images.githubusercontent.com/73544069/153170514-2fe83f21-e306-4729-9e46-749fcd97cb3a.png)

**Comment by segrey** [comment]
@omegaui If I understand correctly, you start jediterm using JediTermMain. If yes, will it help to change `com/jediterm/app/JediTermMain.kt:75` to `setUseWinConPty(true)`?

**Comment by omegaui** [comment]
@segrey 

Well, I have created a class called JetTerminal and this is how it starts Jediterm (using JediTermWidget...
```java
	
	public void init(SettingsProvider jtsp){
		widget = new JediTermWidget(jtsp);

		if(command == null)
			widget.setTtyConnector(getConnector(Screen.onWindows() ? "cmd.exe" : "/bin/bash"));
		else
			widget.setTtyConnector(getConnector(command));
		
		add(widget);
	}
	
	public TtyConnector getConnector(String... command){
		try{
			this.command = command;
			
			Map<String, String> envsX = System.getenv();
			HashMap<String, String> envs = new HashMap<>();
			for(String x : envsX.keySet()){
				envs.put(x, envsX.get(x));
			}
			
			if(!Screen.onWindows())
				envs.put("TERM", "xterm");
			
			process = PtyProcess.exec(command, envs, directory);
			return new PtyProcessTtyConnector(process, Charset.forName("UTF-8"));
		}
		catch(Exception e){
			e.printStackTrace();
		}
		return null;
	}
```

**Comment by omegaui** [comment]
You can see the entire code [here](https://github.com/omegaui/omegaide/blob/defeb8222d7226c95f8863075eb282888247d178/src/omega/ui/component/jediterm/JetTerminal.java#L99-L130)

**Comment by omegaui** [comment]
I tried putting console = true for Windows through PtyProcess.exec but it also didn't helped to gain any performance.

**Comment by omegaui** [comment]
The library is working great on Windows 11 may be there's some problem with windows 10
