### ISSUE TITLE
Any way to set current working directory?

### ISSUE THREAD

**Issue by pskowronek** [JetBrains/jediterm#256]
Any way to set current working directory where the shell is about to be launched?
I would like to avoid artificially calling "cd /to/sth/else".

**Comment by G3G4X5X6** [comment]
![image](https://user-images.githubusercontent.com/87740076/218948389-cf8e80a1-ca5a-4adf-9705-05dcf14e7b05.png)

**Comment by pskowronek** [comment]
Thanks, but this is only for setting CWD for initial instantiation. I was rather asking how to set/change current working directory for an existing instance of Terminal - sorry if I haven't described it more precise.

**Comment by segrey** [comment]
Seems the only way is to write `cd /path/to/dir` string to shell process input stream.
