### ISSUE TITLE
UserSettingsProvider#getSelectionColor() is called way too often

### ISSUE THREAD

**Issue by pskowronek** [JetBrains/jediterm#268]
`UserSettingsProvider#getSelectionColor()` is called way too often - like 3 times per click or any change within terminal.

A brief code analysis shows that `TerminalPanel` calls this method (and the same is for `UserSettingsProvider#getFoundPatternColor()`) directly instead of using `StyleState` as it is being done for `UserSettingsProvider#getDefaultStyle()` - this one is being called only once per initialization.

JediTerm version: 3.17 and master.

**Comment by segrey** [comment]
@pskowronek I tried to optimize it a bit in af3a61ae1ec353532d8aeaad8be79ae8d8bca894, but generally, `UserSettingsProvider#getSelectionColor()` and `UserSettingsProvider#getFoundPatternColor()` could be called multiple times to support switching between different UI themes. I'd recommend to implement some caching in your `UserSettingsProvider` if these methods are expensive.

**Comment by pskowronek** [comment]
Thanks! However, hmm, how does it differ from `UserSettingsProvider#getDefaultStyle()` - it is called once and probably providers/lambdas are called multiple times (which is fine), but `UserSettingsProvider#getSelectionColor()` is called multiple of times even though they also return 'providers'.

**Comment by segrey** [comment]
Do you mean `com.jediterm.terminal.TerminalColor#myColorSupplier` by providers/lambdas?
For example, here is now `com.jediterm.terminal.ui.settings.UserSettingsProvider#getDefaultStyle` is implemented in IntelliJ:
```
  @Override
  public TextStyle getDefaultStyle() {
    return new TextStyle(new TerminalColor(() -> AwtTransformers.fromAwtColor(myUiSettingsManager.getDefaultForeground())),
                         new TerminalColor(() -> AwtTransformers.fromAwtColor(myUiSettingsManager.getDefaultBackground())));
  }
```
So, everything works even if `UserSettingsProvider#getDefaultStyle` is called only once.
I agree with you there is some inconsistency. Probably, these methods should be called only once and dynamic colors should be supported via implementing `Supplier<Color>`.

**Comment by pskowronek** [comment]
> Do you mean `com.jediterm.terminal.TerminalColor#myColorSupplier` by providers/lambdas? For example, here is now `com.jediterm.terminal.ui.settings.UserSettingsProvider#getDefaultStyle` is implemented in IntelliJ:

yes, I haven't had a code in front of me.

> So, everything works even if `UserSettingsProvider#getDefaultStyle` is called only once. I agree with you there is some inconsistency. Probably, these methods should be called only once and dynamic colors should be supported via implementing `Supplier<Color>`.

Yes, that was my thought.
