### ISSUE TITLE
Would you like to provide a demo？

### ISSUE THREAD

**Issue by ZhouMM92** [JetBrains/jediterm#269]
I want to use this in sprint boot, and I want to simulate input and output by this，but I can not find a demo about this.
Would you like to provide a demo？

**Comment by segrey** [comment]
Please check [com.jediterm.example.BasicTerminalExample](https://github.com/JetBrains/jediterm/blob/af3a61ae1ec353532d8aeaad8be79ae8d8bca894/JediTerm/src/main/java/com/jediterm/example/BasicTerminalExample.java) and [com.jediterm.example.BasicTerminalShellExample](https://github.com/JetBrains/jediterm/blob/af3a61ae1ec353532d8aeaad8be79ae8d8bca894/JediTerm/src/main/java/com/jediterm/example/BasicTerminalShellExample.java) out.
